version: '3.7'

services:
    spark:
        build: .
        command: ["sbt"]

        volumes:
            - type: bind
              source: .
              target: /root/mini-project-2

            - type: volume
              source: sbt-deps
              target: /root/.ivy2

            - type: volume
              source: sbt-bin
              target: /root/.sbt

        working_dir: /root/mini-project-2

volumes:
  sbt-deps:
  sbt-bin:
